// <auto-generated />
using System;
using ETD.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETDP.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210012245_AddCurriculumPhasesAndSubjects")]
    partial class AddCurriculumPhasesAndSubjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ETD.Api.Models.CurriculumPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CurriculumPhases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fundamental Learning"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Knowledge Learning"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Practical Learning"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Workplace Experience"
                        });
                });

            modelBuilder.Entity("ETD.Api.Models.QualificationPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurriculumPhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumPhaseId");

                    b.HasIndex("QualificationId", "CurriculumPhaseId")
                        .IsUnique();

                    b.ToTable("QualificationPhases");
                });

            modelBuilder.Entity("ETD.Api.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurriculumPhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NqfLevel")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumPhaseId");

                    b.HasIndex("QualificationId", "CurriculumPhaseId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ETD.Api.Models.QualificationPhase", b =>
                {
                    b.HasOne("ETD.Api.Models.CurriculumPhase", "CurriculumPhase")
                        .WithMany()
                        .HasForeignKey("CurriculumPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurriculumPhase");
                });

            modelBuilder.Entity("ETD.Api.Models.Subject", b =>
                {
                    b.HasOne("ETD.Api.Models.CurriculumPhase", "CurriculumPhase")
                        .WithMany()
                        .HasForeignKey("CurriculumPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurriculumPhase");
                });
#pragma warning restore 612, 618
        }
    }
}
