// <auto-generated />
using System;
using ETD.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETDP.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301115135_AddQualificationCesmField")]
    partial class AddQualificationCesmField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ETD.Api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubtopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubtopicId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("ETD.Api.Models.AssessmentCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CriteriaType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("AssessmentCriteria");
                });

            modelBuilder.Entity("ETD.Api.Models.AutomationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Log")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QualificationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AutomationJobs");
                });

            modelBuilder.Entity("ETD.Api.Models.CurriculumPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CurriculumPhases");
                });

            modelBuilder.Entity("ETD.Api.Models.Demographics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("African")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Asian")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coloureds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Females")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Males")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Other")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalNumberOfStudents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Whites")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WithDisabilities")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QualificationId");

                    b.ToTable("Demographics");
                });

            modelBuilder.Entity("ETD.Api.Models.KnowledgeQuestionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("KnowledgeQuestionnaires");
                });

            modelBuilder.Entity("ETD.Api.Models.LearnerGuide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("LearnerGuides");
                });

            modelBuilder.Entity("ETD.Api.Models.LearnerRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternateIdType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenStatusCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfFisa")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateSubmittedToQcto")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabilityCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabilityRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquityCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalFisaResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenderCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddress1")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddress2")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddress3")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeLanguageCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImmigrantStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerAlternateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerBirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerCellPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerEmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerEnrolledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerFaxNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerHomeAddressPhysicalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerHomeAddressPostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerLastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerMiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionCityTown")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionCityTownPhysicalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionContactPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionContactPersonEmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionContactPersonPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionProvince")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionStreetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionStreetNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalityCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PopiActAgree")
                        .HasColumnType("TEXT");

                    b.Property<string>("PopiActDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalAddress1")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalAddress2")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalAddress3")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvinceCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SdpAccreditationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillsProgrammeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocioeconomicCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatssaAreaCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkExperienceEmployerCityTown")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkExperienceEmployerCityTownCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkExperienceEmployerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkExperienceEmployerProvince")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkExperienceEmployerStreetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkExperienceEmployerStreetNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkExperienceEmployerSupervisorEmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkExperienceEmployerSupervisorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkExperienceEmployerSupervisorPhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LearnerRegistrations");
                });

            modelBuilder.Entity("ETD.Api.Models.LecturerToolkitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentCriteriaDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssessmentCriteriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LearnerActions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningAids")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LecturerActions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonPlanContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LessonPlanDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lpn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QualificationsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LecturerToolkitEntries");
                });

            modelBuilder.Entity("ETD.Api.Models.LessonPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssessmentCriteriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentCriteriaId");

                    b.ToTable("LessonPlans");
                });

            modelBuilder.Entity("ETD.Api.Models.Outcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutcomeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("ETD.Api.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccreditationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CesmField")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Credits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeanPrincipalCEO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LearningDateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LearningDateStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningInstitutionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("NqfLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualificationDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualificationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualificationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeniorLecturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsesOutcomes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("ETD.Api.Models.QualificationPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurriculumPhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumPhaseId");

                    b.HasIndex("QualificationId", "CurriculumPhaseId")
                        .IsUnique();

                    b.ToTable("QualificationPhases");
                });

            modelBuilder.Entity("ETD.Api.Models.SourceMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentCriteriaDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgeLabel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KnowledgeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KnowledgeRootPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("KnowledgeSourceType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("KnowledgeUploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualificationCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualificationDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QualificationDescription", "KnowledgeSourceType", "CreatedAt");

                    b.HasIndex("QualificationCode", "KnowledgeSourceType", "KnowledgeNumber", "KnowledgeUploadedAtUtc");

                    b.ToTable("SourceMaterials");
                });

            modelBuilder.Entity("ETD.Api.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurriculumPhaseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualificationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubjectCredits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubjectNQFLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubjectPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectPurpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumPhaseId");

                    b.HasIndex("QualificationId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ETD.Api.Models.Subtopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Subtopics");
                });

            modelBuilder.Entity("ETD.Api.Models.SystemErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientCorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemErrorLogs");
                });

            modelBuilder.Entity("ETD.Api.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NotionalHours")
                        .HasColumnType("REAL");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutcomeId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PeriodsPerTopic")
                        .HasColumnType("REAL");

                    b.Property<bool>("PeriodsPerTopicManualOverride")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SubjectCredits")
                        .HasColumnType("REAL");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TopicCredits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicDescription")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TopicPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicPurpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OutcomeId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("ETD.Api.Models.Workbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Workbooks");
                });

            modelBuilder.Entity("ETD.Api.Models.Activity", b =>
                {
                    b.HasOne("ETD.Api.Models.Subtopic", "Subtopic")
                        .WithMany("Activities")
                        .HasForeignKey("SubtopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subtopic");
                });

            modelBuilder.Entity("ETD.Api.Models.AssessmentCriteria", b =>
                {
                    b.HasOne("ETD.Api.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ETD.Api.Models.Demographics", b =>
                {
                    b.HasOne("ETD.Api.Models.Qualification", "Qualification")
                        .WithMany("Demographics")
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("ETD.Api.Models.KnowledgeQuestionnaire", b =>
                {
                    b.HasOne("ETD.Api.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ETD.Api.Models.LearnerGuide", b =>
                {
                    b.HasOne("ETD.Api.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ETD.Api.Models.LessonPlan", b =>
                {
                    b.HasOne("ETD.Api.Models.AssessmentCriteria", "AssessmentCriteria")
                        .WithMany("LessonPlans")
                        .HasForeignKey("AssessmentCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentCriteria");
                });

            modelBuilder.Entity("ETD.Api.Models.Outcome", b =>
                {
                    b.HasOne("ETD.Api.Models.Subject", "Subject")
                        .WithMany("Outcomes")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ETD.Api.Models.QualificationPhase", b =>
                {
                    b.HasOne("ETD.Api.Models.CurriculumPhase", "CurriculumPhase")
                        .WithMany()
                        .HasForeignKey("CurriculumPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurriculumPhase");
                });

            modelBuilder.Entity("ETD.Api.Models.Subject", b =>
                {
                    b.HasOne("ETD.Api.Models.CurriculumPhase", "CurriculumPhase")
                        .WithMany("Subjects")
                        .HasForeignKey("CurriculumPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ETD.Api.Models.Qualification", "Qualification")
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumPhase");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("ETD.Api.Models.Subtopic", b =>
                {
                    b.HasOne("ETD.Api.Models.Topic", "Topic")
                        .WithMany("Subtopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ETD.Api.Models.Topic", b =>
                {
                    b.HasOne("ETD.Api.Models.Outcome", "Outcome")
                        .WithMany("Topics")
                        .HasForeignKey("OutcomeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ETD.Api.Models.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outcome");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ETD.Api.Models.Workbook", b =>
                {
                    b.HasOne("ETD.Api.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ETD.Api.Models.AssessmentCriteria", b =>
                {
                    b.Navigation("LessonPlans");
                });

            modelBuilder.Entity("ETD.Api.Models.CurriculumPhase", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ETD.Api.Models.Outcome", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("ETD.Api.Models.Qualification", b =>
                {
                    b.Navigation("Demographics");
                });

            modelBuilder.Entity("ETD.Api.Models.Subject", b =>
                {
                    b.Navigation("Outcomes");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("ETD.Api.Models.Subtopic", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("ETD.Api.Models.Topic", b =>
                {
                    b.Navigation("Subtopics");
                });
#pragma warning restore 612, 618
        }
    }
}
